cray_product_catalog/catalog_update.py

This commit changes the default behavior so that running cray-product-catalog-update does not set a particular version to 'active', unless the SET_ACTIVE_VERSION variable is set in the environment. This makes the behavior more in line with previous versions which were not setting any "active" data.
Tested on: Thanos
Test description: https://gist.github.hpe.com/eli-kamin/56c7fb39a82be251634e854ddbe1b9d0
[N/A] Version number(s) incremented, if applicable
[N/A] Copyrights updated
[Y] License file intact
[Y] Target branch correct
[Y] CHANGELOG.md updated
[Y] Testing is appropriate and complete, if applicable
[N/A] HPC Product Announcement prepared, if applicable**

CRAYSAT-1288: Skip setting active version

---

.github/pull_request_template.md
.github/workflows/gitflow-mergeback.yml
.github/workflows/pr-artifacts.yml
CHANGELOG.md

For some branches (like master), artifact builds are not run because builds are not needed here (tags are built instead). When these commits get merged back to develop, the PR artifact workflow is looking for the build from the commit that was pushed to master, which does not exist.
Instead of trying to determine if the build exists, just let it time out.

let pr artifacts workflow time out and exit

---

CHANGELOG.md
README.md

Remove redundant license/copyright info from README
Also testing what happens from a fork.

Remove redundant license/copyright info from README

---

CHANGELOG.md
GitVersion.yml
README.md

- Remove redundant license/copyright info from README
- CASMFEAT-1234: update README to reference LICENSE FILE
- Default develop increment to Minor in GitVersion config
- Add CSM Gitflow Development link to README
- Update changelog for README modifications
- Prepare release v1.5.0
N/A
None, this PR is just for demonstration purposes.

Release 1.5.0

---

.github/workflows/gitflow-mergeback.yml
CHANGELOG.md

Also fix PRs references to fully reference the repository and PR number instead of just the PR number, which can confuse GitHub autolinking if the reference is included in other repo PRs (such as when release notes are added to a CSM manifest update PR
N/A
N/A

Add automerge capability to git mergeback PRs

---

.github/workflows/changelog-checker.yml
.github/workflows/gitflow-mergeback.yml
.github/workflows/update-csm-manifest.yml
CHANGELOG.md

Remove the auto-approve action from the gitlfow-mergeback.yml workflow.
This did not work as intended and causes a failure in the workflow.
N/A
N/A

Hotfix 1.5.2 - remove auto-approve from merge back workflow

---

.github/workflows/build-artifacts.yml
CHANGELOG.md

Update the image signing and software bill of materials github actions (Cray HPE internal actions) to use the preferred GCP authentication.
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7857
* See builds for this branch
None

Update to sbom/image signing actions using gcp idp

---

.github/templates/deploy-script.sh.tmpl
.github/workflows/build-artifacts.yml
.github/workflows/pr-artifacts.yml
CHANGELOG.md

Update the deploy script to use nexus authentication to push a new docker image to the registry.
* Resolves CASMCMS-7928
* `mug`
Downloaded the script from GH actions output and ran it.
```text
ncn-m001:~/rkleinman # cat image-download-f5bef17.sh
#!/usr/bin/env bash
NEXUS_USERNAME="$(kubectl -n nexus get secret nexus-admin-credential --template {{.data.username}} | base64 -d)"
NEXUS_PASSWORD="$(kubectl -n nexus get secret nexus-admin-credential --template {{.data.password}} | base64 -d)"
echo "Downloading remote image artifactory.algol60.net/csm-docker/unstable/cray-product-catalog-update:1.6.0-CASMCMS-7928.1.20220324151321.f5bef17 to system registry"
podman run --rm --network host quay.io/skopeo/stable copy --src-tls-verify=false --dest-tls-verify=false \ …
```

CASMCMS-7928: Update deploy script for CSM 1.2/Nexus auth

---

.github/workflows/build-artifacts.yml
CHANGELOG.md

In v2 of the `jfrog` CLI, the default value for the `--flat` option changed from true to false. If `--flat` is true, then files are uploaded to the exact target path and their location in the source file system is ignored. If `--flat` is false, then files are uploaded to a target that includes their parent directories on the source file system.
This was resulting in Python modules and helm charts being uploaded into an incorrect location. For example, Python module archives and wheels were uploaded to a `dist` subdirectory in the pip repository and thus could not be found by `pip`.
Fix this problem by specifying `--flat true` on `jfrog rt upload` calls to keep the prior behavior.
* Resolves [CASMCMS-7995](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7995)
* GitHub Actions
* Local …

CASMCMS-7995: Fix the Artifactory upload paths

---

CHANGELOG.md
Dockerfile

Update the base image to alpine:3.15 from the nightly build location.
* Resolves [CASMCMS-7959](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7959)
* `Wasp`
Not tested - can't get this to build before it is merged into develop.
This is a low risk change as we are just updating the base image version for CVE patches.

CASMCMS-7959 - Update alpine base image to newer version.

---

CHANGELOG.md
cray_product_catalog/catalog_delete.py
cray_product_catalog/catalog_update.py
cray_product_catalog/constants.py
cray_product_catalog/query.py
cray_product_catalog/schema/schema.yaml
cray_product_catalog/util.py
requirements.txt
tests/mocks.py
tests/schema/test_schema.py
tests/test_query.py

This adds a new module, `query.py`, which clients can use to query the `cray-product-catalog` Kubernetes ConfigMap to get information about the products installed on the system.
This new module is not exposed as an executable script in the Docker image like `catalog_update` and `catalog_delete`. Rather, it is meant to be used as a library in other Python projects.
This repository is a logical place for such a library because the query code must validate the product catalog data against the schema before processing, and this repository already contains the schema definition and validation code.
The `catalog_update` and `catalog_delete` scripts are mostly unaffected. One minor change was made to define the `load_k8s` function in a common `util` module since it is now used in 3 places.
This …

CRAYSAT-1314: Add product catalog query module

---

CHANGELOG.md
cray_product_catalog/catalog_delete.py
cray_product_catalog/catalog_update.py
cray_product_catalog/util/__init__.py
cray_product_catalog/util/k8s.py
cray_product_catalog/util/merge_dict.py
tests/util/mocks.py
tests/util/test_merge_dict.py

CASM-3555, CASM-3556: Handle concurrent and finer-grained updates
This commit adds a fix to provide better concurrency support when
updating the config map. When patching the config map, specify the
resource_version metadata field. This results in an HTTP 409 (conflict)
error if the target resource_version has unexpectedly changed (i.e.
some other process updated the config map first). This allows the process
to only update the config map when something else has not first updated it.
In order to provide finer-grained updates, introduce a utility function
called merge_dict which will recursively merge a dictionary so that individual
sub-components of the product catalog data can be updated without other
data being overwritten.
This commit also separates the util module into separate files, …

CASM-3555, CASM-3556: Handle concurrent and finer-grained updates

---

CHANGELOG.md
README.md
cray_product_catalog/catalog_update.py

In order to support running `cray-product-catalog-update` in an Argo workflow more easily, provide the ability to pass YAML content in string form rather than just in file form.
Test Description: I built this image and ran an argo workflow to insert the data into the product catalog.
See commit message. This change is fully backwards compatible.
* Required for CASM-3518
Tested locally in minikube

CASM-3518: Add the ability to specify raw yaml content

---

.github/workflows/license-check.yaml
CHANGELOG.md

This commit adds a workflow definition to run the license checker. This workflow is copied verbatim from the Cray-HPE/docs-csm repository.
See commit message.
* Required as part of CASM-3518
Tested as a part of the pull request
N/A

CASM-3518: Add license check workflow

---

.github/workflows/license-check.yaml
CHANGELOG.md
README.md
cray_product_catalog/catalog_delete.py
cray_product_catalog/catalog_update.py
cray_product_catalog/logging.py

See commit messages:
* Add log format so that messages are prefixed with severity per IUF guidelines
* Modify license check job so that authenticated access is used to access artifactory.
* Add an environment variable for the removal of the "active" field.
* CASM-3698
* CASMINST-5440
* CRAYSAT-1644
* Local development system
See commit messages

Log format, license check fix and add option to remove 'active' field.

---

CHANGELOG.md
cray_product_catalog/util/merge_dict.py
tests/util/test_merge_dict.py

This commit changes the behavior of the 'merge_dict' utility, such that duplicate entries in a list are now replaced. Add a unit test for this behavior.
The behavior was changed to prevent an infinite loop in the product catalog update process. The main loop in update_catalog breaks out of the loop only if merging in new content would do nothing (i.e.; it does a merge of the input data into the current catalog data and checks if it was unchanged. However, when merging a dictionary containing lists that do not remove duplicates, the resulting data will always change, leading to the process looping forever.
In addition to this issue in the logic, it probably makes more sense to not allow duplicate lists of dictionaries in the catalog. For example, if a partial install were to insert some of …

CASM-3589: Remove duplicate entries when merging dictionaries

---

CHANGELOG.md
charts/cray-product-catalog/Chart.yaml
update_versions.conf

The helm chart had a bad image path, injected with commit b9df79f175eb93a10511433e44b5e5b555ce70a9

CASMCMS-8521: Fixed bad image path in chart

---

CHANGELOG.md
README.md
cray_product_catalog/catalog_update.py

The config map needs to support functionality that allows the keys to be overwritten when necessary. This is to allow scenarios where deleting a single key from the config is possible without having to perform a full delete of the map and then update.
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves https://jira-pro.it.hpe.com:8443/browse/CASM-3973
* `Mug`
Removal of nexus helm charts and configmap updates.

CASM-3973: Adding overwrite update to support key deletions.

---

.github/workflows/charts-lint-test-scan.yml
.github/workflows/license-check.yaml
CHANGELOG.md
README.md
constraints.txt
cray_product_catalog/catalog_update.py

Release notes:
- dependabot: Bump `requests` from 2.30.0 to 2.31.0
- dependabot: Bump `google-auth` from 2.17.3 to 2.20.0
- dependabot: Bump `cachetools` from 5.3.0 to 5.3.1
- dependabot: Bump `websocket-client` from 1.5.2 to 1.6.1
- Added `UPDATE_OVERWRITE` environment variable to support cases where
full control of the products configmap data is required.
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves partially [CASM-3973](https://jira-pro.it.hpe.com:8443/browse/CASM-3973)
* Merge before `https://github.com/Cray-HPE/shasta-install-utility-common/pull/8`

Release 1.8.9

---

CHANGELOG.md
Dockerfile
constraints.txt
requirements-non-pyyaml.txt
requirements-pyyaml.txt

Cray Product Catalog builds started failing recently, due to https://github.com/yaml/pyyaml/issues/601. Because CPC is using an Alpine container, and because the `kubernetes` Python module has a dependency on `PyYAML` >= 5.4, this PR represents the simplest workaround I was able to come up with. (Essentially, it forces the install of `PyYAML` inside the Docker container to use an older version of Cython). The PR is careful to only make this change when installing the `PyYAML` module and (because it has a dependency on `PyYAML`) the `kubernetes` module. I tried doing it with the modification limited to the `PyYAML` module, but the problem persisted until I pulled the `kubernetes` module in as well.
This should only be a temporary workaround. There is a PR up for `PyYAML` that will allow us …

CASMCMS-8713: Temporarily modify PyYAML, kubernetes install procedure

---

CHANGELOG.md
cray_product_catalog/catalog_update.py
tests/test_update_catalog.py

One of the logging calls was tricking IUF into thinking that the update failed, when in fact it had not. I corrected that with this PR, and also added a little more information to a few other logging calls.
I also changed the `create_config_map` function in the `catalog_update` module so that it raises an exception to indicate failure, rather than returning a boolean. This allows for simpler debugging in the case that it fails. It is also the reason I chose to bump the minor number with this change. Even though that function is new in version 2.0, and thus I doubt anyone has written any Python code to use it outside of this repo, it nevertheless is a breaking change which should not be under a mere patch number bump.
[CASMTRIAGE-6794](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6794 …

CASMTRIAGE-6794: Improve logging in catalog_update

---

CHANGELOG.md
Dockerfile
setup.py
update_versions.conf

This will allow the Python module to be installed from source (rather than just from the wheel).

CASMCMS-9012: Allow Python module installs from source to work

---

CHANGELOG.md
cray_product_catalog/catalog_delete.py
cray_product_catalog/migration/config_map_data_handler.py
cray_product_catalog/migration/main.py
setup.py
tests/migration/migration_mock.py
tests/migration/test_config_map_data_handler.py
tests/test_catalog_delete.py

The changes are related to the new format of cray-product-catalog . The PR involves changes for three JIRAs attached below.
Two of them are bug fixes (4741 and 4743).
The third one involves design change to make the format of cray-product-catalog after migration more efficient and compatible. (4731) 
More details are present in the JIRA regarding all the code changes.
Also there is a change in setup.py to make use of the cpc module in iuf-cli code .
* Resolves [CASM-4731](https://jira-pro.it.hpe.com:8443/browse/CASM-4731), [CASM-4743](https://jira-pro.it.hpe.com:8443/browse/CASM-4743), [CASM-4741](https://jira-pro.it.hpe.com:8443/browse/CASM-4741)
* starlord

CASM-4727: Migrate all products to latest version of cpc

---

CHANGELOG.md
Dockerfile
MANIFEST.in
setup.py

This reverts most of the changes in [this commit](https://github.com/Cray-HPE/cray-product-catalog/commit/0f0eec53d5e1d53ec58b2e46e96ef16b3e99b6e5) and instead creates a `MANIFEST.in` file to include the necessary files in order for source installs of the module to work.
The one exception is that I did not revert the version change, but that is just because the version string was being dynamically set either way, and this way is simpler than the previous way.
Thanks to @haasken-hpe for the help with this,

CASMCMS-9098: Restore long_description and install_requires to setup.py

---

CHANGELOG.md
charts/cray-product-catalog/Chart.yaml
charts/cray-product-catalog/values.yaml

To keep up with the k8s api, update the version of the docker-kubectl image being used to update the product catalog.
* Resolves [CASMCMS-9132](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9132)
* `Mug`
Created an updated manifest with the new product-catalog and image version overrides in the csm-config and barebones image impor jobs, then installed with loftsman. Verified the imports happened correctly and the product catalog was updated.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N
- Were continuous integration tests run? If not, why? N
- Was upgrade tested? If not, why? Y
- Was downgrade tested? If not, why? Y
- Were new tests (or test issues/Jiras) created for this change? N
This is a low risk change - just keeping up with the …

CASMCMS-9132 - update the version of docker-kubectl for k8s 1.24
